### PR TITLE
Mobile friendly

### PR DESCRIPTION
**Pull request by themrb**
Couple more tweaks
- Put warning back, but made body padding readjust to top navbar height change events to reclaim the space
- Hid zoom controls for mobiles
- Made mobiles not open filter panel on cooldown (just because it hides everything on small screens)
- only allow one panel at a time on narrow clients
- hide other controls when panel is open on very narrow clients
- collapsible heading (chevron show on bootstrap xs)

### CODE REVIEW

**Comment by themrb** [comment]
@ptim can you have a look?

**Comment by techieshark** [comment]
This does seem like an improvement over what there is now.

Another improvement could be putting share buttons on one line so we save vertical space.

image

could be:
image

(`float: right` on social buttons, and `clear: both` on twitter button)

**Comment by themrb** [comment]
Thanks @techieshark! I've added your suggestion, and gone a step further to inline the social buttons with the AEC link - please take another look.

**Comment by techieshark** [comment]
@themrb, I've included your changes and a few more in this branch. Can you take a look?

https://github.com/techieshark/donations-visualiser/tree/features/27-mobile-support

(This relates to issue #27)

**Comment by themrb** [comment]
@techieshark I like what you've done a lot, your branch greatly enhances the experience for 320px width screens. Thanks for doing the merge too.

Just for tidiness can you do a git rebase to squash your last 5 commits (leaving the whitespace changes as its own commit)? After that if you create a pull request I will merge it in.

**Comment by river-jade** [comment]
hey guys, sorry for being out of the loop. did the rebase happen? can we
merge this in?

**Comment by techieshark** [comment]
@river-jade thanks for the poke. 

@themrb I rebased as suggested and there's a new PR with that here: https://github.com/river-jade/donations-visualiser/pull/28

**Comment by themrb** [comment]
Great, going to close this PR now, functionality has been pulled in as part of #28

**Pull request closed without merging**
